### ISSUE TITLE
Any way to contact developpers ?

### ISSUE THREAD

**Issue by gpernot** [AwesomeFoodCoops/odoo-production#455]
Hi,

i'm trying to set up an odoo for supercafoutch in marseille, but i lack some information (needed odoo version, easiest distribution to use, ...).
Is there any way to get in touch with someone who got this running ? @yuntux @legalsylvain maybe ?

regards,
guillaume

**Comment by yuntux** [comment]
Simon, un nouveau client pour toi.

2018-03-07 11:03 GMT+01:00 gpernot <notifications@github.com>:

**Comment by simonjejcic** [comment]
Bonjour Guillaume,

Peux-tu nous contacter à cette adresse stp ?
dsi.erp@cooplalouve.fr

On peut s'appeler si tu es disponible en semaine soit le matin 9h-9h30 soit
le soir 18h30-19h30

À bientôt,
Simon

**Comment by gpernot** [comment]
yep,

7 mars 2018 12:46 "yuntux" <notifications@github.com> a écrit:
> Simon, un nouveau client pour toi.

super ! j'ai pris contact.

merci,
a++
